### ISSUE TITLE
[Bug]: npm_translate_lock doesn't follow package resolution of pnpm-lock.yaml with private registry

### ISSUE THREAD

**Issue by SinimaWath** [aspect-build/rules_js#1479]
## Description

If I have.npmrc with private registry:
```
registry=https://private.registry.dev/npm

# https://docs.aspect.build/rulesets/aspect_rules_js/docs/pnpm/#hoisting
hoist=false

```

And if I install 2 packages, one from private registry, one from public:
```json
    "dependencies": {
        "chalk": "5.0.1",
        "@private/example": "1.0.0"
    }
```

pnpm-lock.yaml may omit default registry, to safe a space on the disk:
```yaml
packages:

  /@private/example@1.0.0:
    resolution: {integrity: <...>, tarball: https://private.registry.dev/npm/@private/example/-/@private/example-1.0.0.tgz}
    dev: false

  /chalk@5.0.1:
    resolution: {integrity: sha512-Fo07WOYGqMfCWHOzSXOt2CxDbC6skS/jO9ynEcmpANMoPrD+W1r1K6Vx7iNm+AQmETU1Xr2t+n8nzkV9t6xh3w==}
    engines: {node: ^12.17.0 || ^14.13 || >=16.0.0}
    dev: false
```

As you see `chalk@5.0.1:`, doesn't have specification of tarball or registry, but pnpm will download chalk from `private.registry.dev` as it's have info in node_modules/.modules.yaml:
```yaml
hoistedDependencies: {}
included:
  dependencies: true
  devDependencies: true
  optionalDependencies: true
injectedDeps: {}
layoutVersion: 5
nodeLinker: isolated
packageManager: pnpm@8.15.2
pendingBuilds: []
prunedAt: Wed, 14 Feb 2024 22:14:58 GMT
publicHoistPattern:
  - '*eslint*'
  - '*prettier*'
registries:
  default: https://private.registry.dev/npm/
skipped: []
storeDir: ...
virtualStoreDir: ....

```

## Actual 

rules_js will download it from defaultRegistry in [rules_js](https://github.com/aspect-build/rules_js/blob/main/npm/private/utils.bzl#L312) for now is `registry.npmjs.org/`

## Expected

rules_js will install chalk as an pnpm from https://private.registry.dev/npm/

### Version

Development (host) and target OS/architectures: MacOS darwin arm64

Output of `bazel --version`: 7.0.2

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:
1.37.1

Language(s) and/or frameworks involved: pnpm@8.15.2

### How to reproduce

```shell
See What happend
```

## Workaround

Patch default_registry in rules_js with override in MODULE

```patch
--- a/npm/private/utils.bzl
+++ b/npm/private/utils.bzl
@@ -309,7 +309,7 @@ def _to_registry_url(url):
     return "{}://{}".format(DEFAULT_REGISTRY_PROTOCOL, url) if url.find("//") == -1 else url
 
 def _default_registry():
-    return _to_registry_url("registry.npmjs.org/")
+    return _to_registry_url("https://private.registry.dev")
 
 def _hash(s):
     # Bazel's hash() resolves to a 32-bit signed integer [-2,147,483,648 to 2,147,483,647].

```
